export const siteConfig = {
  name: "Євростандарти Офісу",
  domain: "european.com.ua",
  url: "https://european.com.ua",
  language: "uk",
  locale: "uk_UA",
  description: "Портал про європейські стандарти організації офісного простору — ергономіка, акустика, продуктивність. Норми EN та ISO для сучасного офісу.",
  ogImage: "/images/og-cover.jpg",
  favicon: "/images/favicon.svg",
  keywords: ["європейські стандарти офісу", "ергономіка офісу", "акустичні кабіни для офісу", "офісні кабіни", "звукоізоляційні кабіни", "кабіни для переговорів", "організація офісного простору", "звукоізоляція офісу"],
  crmWebhookUrl: "https://office.silent-box.com/api/pbn/webhook",
  phone: "+380 44 000 00 00",
  address: "м. Київ, Україна",
  workingHours: "Пн-Пт: 09:00 - 18:00",
}
